language: python

python:
  - "3.7"

install:
  - pip install nala

script:
  - source setup.sh
  - make -s -j $(cat /proc/cpuinfo | grep processor | wc -l) all
  - make release
  - make release-compile

after_success:
  - bash <(curl -s https://codecov.io/bash) -X coveragepy
