TESTS += test_core_channel.c
TESTS += test_core_core.c
TESTS += test_core_runtime_null.c
TESTS += test_core_tcp_client.c
TESTS += test_core_tcp_server.c
TESTS += test_core_timer.c
TESTS += test_mqtt_client.c
TESTS += test_shell.c
TESTS += test_runtime.c

include test.mk
