TESTS += test_core_channel.c
TESTS += test_core_core.c
TESTS += test_core_tcp_client.c
TESTS += test_core_timer.c
TESTS += test_modules_mqtt_client.c
TESTS += test_modules_shell.c

include $(ASYNC_ROOT)/make/suite.mk
